# Generated by Django 4.2.4 on 2023-08-07 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food_model',
            options={'verbose_name_plural': 'food_Models'},
        ),
    ]
